### PR TITLE
Fix DeleteCommandParser to handle invalid day and index correctly

### LINKED ISSUE #147: Deletelesson shows invalid command format instead of invalid index for non-positive indices and invalid day
When a user provides an index <= 0 in the deletelesson command, the message displayed is "invalid command format."
It should instead indicate "invalid index" to accurately reflect the problem and guide the user correctly.

When a user provides an invalid day as in the deletelesson command, the message displayed is "invalid command format."
It should instead indicate Day.MESSAGE_CONSTRAINTS to accurately reflect the problem and guide the user correctly.

### PR DESCRIPTION
**Pull request by gunawanjoseph**
Close #147

### CODE REVIEW

**Comment by gunawanjoseph** [comment]
Please merge the UML diagram first. Thanks!

File: src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java [hunk 1]
```diff
@@ -19,31 +19,29 @@ public class DeleteLessonCommandParser implements Parser<DeleteLessonCommand> {
      * @throws ParseException if the user input does not conform the expected format
      */
     public DeleteLessonCommand parse(String args) throws ParseException {
-        try {
-            String trimmedArgs = args.trim();
-            String[] argParts = trimmedArgs.split("\\s+");
+        String trimmedArgs = args.trim();
```
Comment (zzdlklzz) [inline src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java]: Could we perhaps use the ArgumentMultimap instead for standardization across other commands?

**Review by kianshenteoh — APPROVED** [review]
LGTM
